import sys
import os
import shutil

# Add project root
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '../'))
sys.path.append(PROJECT_ROOT)

try:
    from agents.documents.document_builder import DocumentBuilder
    from agents.documents.tikz_expert import TikZExpert
except ImportError as e:
    print(f"Error importing agents: {e}")
    sys.exit(1)

def run_test():
    print("Starting Phase 4 Integration Test...\n")
    
    # Check if pdflatex is installed but proceed with test logic
    has_latex = shutil.which("pdflatex") is not None
    if not has_latex:
        print("'pdflatex' not found. Tests will run in mock mode.\n")

    # 1. Generate TikZ Figure
    print("--- 1. Generating TikZ Figure ---")
    expert = TikZExpert()
    parabola = expert.generate_figure("draw a parabola")
    print(f"TikZ Code:\n{parabola['latex'][:100]}...\n")

    # 2. Build Document
    print("--- 2. Building Document ---")
    builder = DocumentBuilder()
    
    content = f"""
    \\section{{Introduction}}
    This is a test document generated by EduTeX Agents.
    
    \\section{{Figure}}
    Here is a generated plot:
    \\begin{{center}}
    {parabola['latex']}
    \\end{{center}}
    """
    
    # We'll use a temp file name
    output_tex = "test_phase4_output.tex"
    result = builder.build_document(content, title="Phase 4 Test", output_filename=output_tex)
    
    print(f"Status: {result['status']}")
    print(f"TeX Path: {result['tex_path']}")
    print(f"PDF Path: {result['pdf_path']}")
    
    if os.path.exists(output_tex):
        print(f"TeX file created successfully.")
        
        # Cleanup if successful
        try:
            # os.remove(output_tex)
            pass 
        except: pass
        
    print("\nPhase 4 Test Complete!")

if __name__ == "__main__":
    run_test()
